name: Update Video Stars data

on:
  workflow_dispatch:
  schedule:
    - cron: "* * 1 * *"
  push:
    branches:
      - "main"
    paths:
      - "video_stars.py"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: code
      
      - name: Checkout data
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: data
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: | 
          python -m pip install roblox==2.0.0
      
      - name: Fetch data
        run: | 
          cd data
          python ../code/video_stars.py
      
      
      - name: Deploy to branch
        run: |
          cd data
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update Video Stars data"
          git push
